name: Metrics
on:
  # Schedule updates (each half day)
  schedule: [{cron: "0 0,12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: METRICS_TOKEN
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: juzi5201314
          template: classic
          base: header, topics, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_aliases: RenderScript:Rust
          plugin_languages_limit: 16
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_notable: yes
          plugin_notable_filter: star:>500
          plugin_notable_from: all
          plugin_traffic: yes
